spring:
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  application:
    name: sound-hub-modular
  datasource:
    url: jdbc:mysql://localhost:3306/sound-hub
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootroot}
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active:

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: eu-north-1
    bucket: soundhub7
    folders:
      band-images: band-images
      user-images: user-images

server:
  port: 8080